# -*- coding: utf-8 -*-
"""Airbnb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D27saL5SDotqv2A_rSjCATb2eD6G7AzS

# **Project Name**    - Airbnb Data Analysis & Insights

##### **Project Type**    - Exploratory Data Analysis (EDA)

##Key Items

- Data Exploration → Understanding variables like price, reviews, availability, and location.
- Business Insights → Identifying demand drivers (room type, neighbourhood, pricing strategy).
- Visualization → Using histograms, scatterplots, bar charts, heatmaps, and pair plots to uncover patterns.
- Recommendations → Suggesting strategies for hosts and Airbnb to optimize pricing, availability, and customer engagement.



##### **Contribution**    - Individual

# **Project Summary -**

Airbnb has revolutionized the travel industry by offering unique, affordable, and personalized stays across the globe. Since its inception in 2008, Airbnb has grown into a platform hosting millions of listings, generating vast amounts of data. This dataset, containing ~49,000 listings with 16 attributes, offers insights into host behavior, customer preferences, pricing strategies, and availability patterns.

The project aims to explore and analyze this dataset to uncover meaningful trends. We begin with data cleaning: removing duplicates, handling missing values (e.g., reviews per month, last review dates), and treating outliers (e.g., capping extreme prices). Once the dataset is prepared, we perform Univariate, Bivariate, and Multivariate analyses (UBM) to understand distributions, relationships, and correlations.

Univariate analysis highlights the distribution of room types, prices, availability, and reviews. For example, private rooms and entire homes dominate listings, while shared rooms are rare. Price distributions show a heavy right tail, requiring capping to avoid skewed insights.

Bivariate analysis explores relationships between categorical and numerical variables. Boxplots reveal that entire homes are significantly more expensive than private or shared rooms. Bar charts show neighborhood groups like Manhattan commanding higher average prices. Scatterplots demonstrate that affordable listings tend to attract more reviews, while high-priced listings often remain under-reviewed.

Multivariate analysis combines multiple variables to uncover deeper insights. Pair plots and correlation heatmaps highlight relationships among price, reviews, minimum nights, and availability. Faceted boxplots show how price varies simultaneously by room type and neighborhood group.
These insights have direct business implications. Airbnb can optimize pricing strategies by room type and location, promote affordable high-review listings to boost conversions, and identify inactive or underperforming listings for host coaching. Hosts can use these findings to adjust pricing, improve listing quality, and maximize occupancy.

In conclusion, this EDA project demonstrates how structured data analysis can transform raw information into actionable business intelligence. By following a clear workflow—data cleaning, hypothesis formation, visualization, and storytelling—we provide Airbnb with insights that enhance customer satisfaction, improve host performance, and strengthen the platform’s competitive edge.

# **GitHub Link -**

https://github.com/abhigorde2209-prog/Airbnb-Data-Analysis-Insights

# **Problem Statement**

**Analyze Airbnb listings data to understand how room type, location, reviews, and availability influence pricing and demand**

#### **Define Your Business Objective?**

- Optimize pricing strategies across room types and neighborhoods.
- Identify high-demand areas and value segments for targeted marketing.
- Improve listing health by spotlighting inactive or low-performing listings.

# **General Guidelines** : -

1.   Well-structured, formatted, and commented code is required.
2.   Exception Handling, Production Grade Code & Deployment Ready Code will be a plus. Those students will be awarded some additional credits.
     
     The additional credits will have advantages over other students during Star Student selection.
       
             [ Note: - Deployment Ready Code is defined as, the whole .ipynb notebook should be executable in one go
                       without a single error logged. ]

3.   Each and every logic should have proper comments.
4. You may add as many number of charts you want. Make Sure for each and every chart the following format should be answered.
        

```
# Chart visualization code
```
            

*   Why did you pick the specific chart?
*   What is/are the insight(s) found from the chart?
* Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

5. You have to create at least 20 logical & meaningful charts having important insights.


[ Hints : - Do the Vizualization in  a structured way while following "UBM" Rule.

U - Univariate Analysis,

B - Bivariate Analysis (Numerical - Categorical, Numerical - Numerical, Categorical - Categorical)

M - Multivariate Analysis
 ]

# ***Let's Begin !***

## ***1. Know Your Data***

### Import Libraries
"""

# Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""### Dataset Loading"""

# Load Dataset
# mounted google drive
#from google.colab import drive
# drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Airbnb/Airbnb_NYC.csv")

"""### Dataset First View"""

# Dataset First Look
print(df.head())

"""### Dataset Rows & Columns count"""

# Dataset Rows & Columns count
print(df.shape)

"""### Dataset Information"""

# Dataset Info
print(df.info())

"""#### Duplicate Values"""

# Dataset Duplicate Value Count
print("Duplicates:", df.duplicated().sum())

#len(df[df.duplicated()])

"""#### Missing Values/Null Values"""

# Missing Values/Null Values Count
print(df.isna().sum())

# Visualizing the missing values
#plt.figure(figsize=(10,6))
sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
#plt.title("Missing Values Heatmap")
#plt.show()

"""### What did you know about your dataset?

- The dataset contains approximately 49,000 rows and 16 columns
- Because only 16 and 21 rows are missing out of ~49,000, those yellow lines are very thin and sparsein the heatmap

## ***2. Understanding Your Variables***
"""

# Dataset Columns
print(df.columns)

# Dataset Describe
print(df.describe(include="all"))

"""### Variables Description

Variables include categorical (room_type, neighborhood_group) and numerical (price, reviews, availability).

- id → Unique identifier for each listing.
- name → Title or description of the listing (text field, sometimes missing).
- host_id → Unique identifier for the host.
- host_name → Name of the host (categorical, sometimes missing).
- neighbourhood_group → Broad location category (e.g., Manhattan, Brooklyn, Queens, Bronx, Staten Island).
- neighbourhood → Specific neighborhood within the group.
- latitude → Geographic coordinate (north–south position).
- longitude → Geographic coordinate (east–west position).
- room_type → Type of accommodation (Entire home/apt, Private room, Shared room).
- price → Nightly price of the listing (numeric, contains outliers).
- minimum_nights → Minimum nights required to book (numeric, sometimes unrealistic values like >365).
- number_of_reviews → Total number of reviews received for the listing.
- last_review → Date of the most recent review (missing for listings with no reviews).
- reviews_per_month → Average number of reviews per month (missing values imputed with 0).
- calculated_host_listings_count → Number of listings managed by the s- ame host.
- availability_365 → Number of days the listing is available in a year (0–365).

### Check Unique Values for each variable.
"""

# Check Unique Values for each variable.
for col in df.columns:
    print(col, df[col].nunique())

"""## 3. ***Data Wrangling***

### Data Wrangling Code
"""

# Write your code to make your dataset analysis ready.

# Remove duplicates
df = df.drop_duplicates()

# Drop rows with missing host_name or name (very few, negligible impact)
df = df.dropna(subset=['host_name', 'name'])



# Handle missing values
df['reviews_per_month'] = df['reviews_per_month'].fillna(0)
df['last_review'] = pd.to_datetime(df['last_review'], errors='coerce')

# Cap extreme prices
price_cap = df['price'].quantile(0.99)
df['price'] = np.where(df['price'] > price_cap, price_cap, df['price'])

# Cap extreme outliers in minimum_nights (reasonable threshold, e.g., 365)
df['minimum_nights'] = np.where(df['minimum_nights'] > 365, 365, df['minimum_nights'])

# Ensure availability is within valid range (0–365)
df['availability_365'] = df['availability_365'].clip(0, 365)

# Price per night (normalize by minimum nights)
df['price_per_night'] = df['price'] / df['minimum_nights']

# Helpful derived fields
df["is_shared"] = df["room_type"].eq("Shared room").astype(int)
df["is_private"] = df["room_type"].eq("Private room").astype(int)
df["is_entire"] = df["room_type"].eq("Entire home/apt").astype(int)

def show(title):
    plt.title(title)
    plt.tight_layout()
    plt.show()

print(df.head())
print(df.info())

"""### What all manipulations have you done and insights you found?

We have now cleaned duplicates, handled missing values, capped outliers, and corrected invalid ranges. The dataset is now analysis‑ready and aligned with your project objective: understanding how room type, location, reviews, and availability influence pricing and demand.
Would you like me to now summarize this in a polished “Data Wrangling → Manipulations & Insights” section that you can paste directly into your project report?

1. Duplicates:
-  None remained → dataset integrity is strong.

2. Missing values:
-   Reviews_per_month now analysis‑ready with 0s.
- last_review properly formatted for time‑based analysis.
- Minimal missing name/host_name rows removed without affecting dataset size.

3. Price distribution:
- Extreme outliers capped → average and median prices now more realistic.
- Prevents skew in demand vs pricing analysis.

4. Minimum nights:
- Unrealistic values (>365) corrected → booking behavior analysis is now meaningful.

5. Availability:
- Listings are now constrained to valid ranges, ensuring accurate supply analysis.

6. Dataset readiness:
- Clean, consistent, and reliable for EDA on room type, location, reviews, and availability vs pricing/demand.

## ***4. Data Vizualization, Storytelling & Experimenting with charts : Understand the relationships between variables***

#### Chart - 1
"""

# Chart - 1 visualization code

import seaborn as sns
import matplotlib.pyplot as plt

# Countplot for room types
sns.countplot(data=df, x="room_type", palette="Set2")
plt.title("Room Type Distribution")
plt.xlabel("Room Type")
plt.ylabel("Count of Listings")
plt.show()

"""##### 1. Why did you pick the specific chart?

- It’s a univariate analysis of the categorical variable room_type.
- Helps us understand the composition of listings (Entire home/apt, Private room, Shared room).

##### 2. What is/are the insight(s) found from the chart?

- Private rooms and entire homes dominate the dataset.
- Shared rooms are very rare, showing limited supply.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Positive: Airbnb can focus marketing on the most common room types (private rooms and entire homes).
- Negative growth risk: Shared rooms may not generate significant revenue due to low supply and demand.
- Justification: Understanding inventory mix helps Airbnb optimize pricing and promotions for the most popular categories.

#### Chart - 2
"""

# Chart - 2 visualization code
sns.histplot(df["price"], bins=50, kde=True, color="skyblue")
plt.title("Price Distribution (Capped at 99th Percentile)")
plt.xlabel("Price")
plt.ylabel("Count")
plt.show()

"""##### 1. Why did you pick the specific chart?

To understand the spread of listing prices.

##### 2. What is/are the insight(s) found from the chart?

Most listings are under $500; extreme outliers exist but were capped.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

Understanding the overall distribution of prices helps Airbnb set pricing benchmarks and detect outliers. By knowing that most listings cluster under $500, Airbnb can:
- Guide hosts to price competitively within the main demand range.
- Identify and correct unrealistic pricing that could discourage bookings.
- Improve customer satisfaction by ensuring price transparency and affordability

#### Chart - 3
"""

# Chart - 3 visualization code
sns.histplot(df["availability_365"], bins=40, color="orange")
plt.title("Availability (days/year) Distribution")
plt.xlabel("Days Available")
plt.ylabel("Count")
plt.show()

"""##### 1. Why did you pick the specific chart?

- A histogram is the best way to visualize the distribution of a continuous variable like availability_365.
- It shows how listings are spread across the possible range (0–365 days).
- Using bins helps identify clusters (e.g., listings available all year vs seasonal availability).

##### 2. What is/are the insight(s) found from the chart?

1. Peaks at 0 and 365 days:
- Many listings are either never available (0 days) or always available (365 days).
- This suggests two types of hosts: inactive/temporary vs commercial/full‑time.
2. Seasonal availability:
- Smaller peaks may appear around 30, 90, 180 days → indicating hosts who rent for specific seasons or months.
3. Skewed distribution:
- The dataset is not evenly spread; most listings fall into extreme categories (0 or 365).

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Demand forecasting: Airbnb can predict supply availability more accurately by knowing how many listings are active year‑round vs seasonal.
- Host engagement: Identifying inactive listings (0 days) helps Airbnb reach out to hosts to encourage activation.
- Customer experience: Travelers benefit from knowing which listings are reliably available, improving booking confidence.
- Revenue optimization: Year‑round listings can be priced differently than seasonal ones, maximizing profitability

#### Chart - 4
"""

# Chart - 4 visualization code

plt.figure(figsize=(8,6))
sns.histplot(df["number_of_reviews"], bins=50, color="green")
plt.title("Distribution of Number of Reviews")
plt.xlabel("Number of Reviews")
plt.ylabel("Count of Listings")
plt.xlim(0, 200)  # cap for readability, avoids extreme outliers
plt.show()

"""##### 1. Why did you pick the specific chart?

- A histogram is ideal for showing how reviews are distributed across listings.
- It highlights whether most listings have few reviews or if there are many highly‑reviewed properties.
- Reviews are a proxy for demand — more reviews usually mean higher customer engagement.

##### 2. What is/are the insight(s) found from the chart?

- Majority of listings have very few reviews (cluster near 0–20).
- Long tail distribution: a small number of listings have hundreds of reviews, showing they are highly popular.
- Skewed pattern: demand is concentrated in a limited set of listings, while many remain under‑reviewed.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Host coaching: Airbnb can encourage hosts with few reviews to improve listing quality and attract demand.
- Customer trust: Listings with many reviews can be promoted as “highly reliable,” boosting bookings.
- Demand forecasting: Identifies which listings drive most of the platform’s engagement.
- Revenue optimization: Helps Airbnb design pricing strategies around high‑review vs low‑review listings.

#### Chart - 5
"""

# Chart - 5 visualization code
plt.figure(figsize=(8,6))
sns.scatterplot(x="number_of_reviews", y="price", data=df, alpha=0.5, color="purple")
plt.title("Number of Reviews vs Price")
plt.xlabel("Number of Reviews")
plt.ylabel("Price (USD per night)")
plt.ylim(0, 600)   # cap y-axis for readability
plt.xlim(0, 200)   # cap x-axis for readability
plt.show()

"""##### 1. Why did you pick the specific chart?

- A scatterplot is ideal for showing the relationship between two continuous variables: reviews and price.
- It helps identify whether cheaper listings attract more reviews, or if higher‑priced listings also sustain demand.
- This directly addresses the business objective: how reviews influence pricing and demand.

##### 2. What is/are the insight(s) found from the chart?

- Listings with lower prices tend to have more reviews, showing stronger demand.
- High‑priced listings generally have fewer reviews, suggesting limited demand at premium rates.
- A few exceptions exist (luxury listings with many reviews), but the overall trend shows inverse relationship between price and reviews.
- The scatterplot highlights clusters of popular budget listings that dominate customer engagement.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Pricing strategy: Hosts can set competitive prices to attract more reviews and bookings.
- Demand forecasting: Airbnb can predict which listings will generate higher engagement based on price bands.
- Customer trust: Listings with many reviews at affordable prices can be promoted to boost conversions.
- Revenue optimization: Helps balance between premium pricing and customer demand.

#### Chart - 6
"""

# Chart - 6 visualization code

plt.figure(figsize=(8,6))
sns.barplot(x="neighbourhood_group", y="price", data=df, estimator=np.mean, ci=None, palette="Set2")
plt.title("Average Price by Neighbourhood Group")
plt.xlabel("Neighbourhood Group")
plt.ylabel("Average Price (USD per night)")
plt.show()

"""##### 1. Why did you pick the specific chart?

- A barplot is ideal for comparing average prices across categorical groups.
- It clearly shows how location (neighbourhood group) influences pricing.
- This directly supports the business objective: understanding how location impacts demand and pricing.

##### 2. What is/are the insight(s) found from the chart?

- Manhattan → highest average prices, confirming it as the premium market.
- Brooklyn → moderately priced, with strong demand due to affordability compared to Manhattan.
- Queens, Bronx, Staten Island → lower average prices, catering to budget travelers.
- Clear price segmentation by location emerges, showing how geography drives pricing strategy.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Pricing strategy: Hosts can benchmark their prices against the average in their neighbourhood group.
- Demand forecasting: Airbnb can predict which areas will attract premium vs budget travelers.
- Customer experience: Travelers can choose locations based on affordability and demand.
- Revenue optimization: Helps Airbnb balance supply between high‑price and budget areas.

#### Chart - 7
"""

# Chart - 7 visualization code

plt.figure(figsize=(8,6))
sns.barplot(x="room_type", y="number_of_reviews", data=df, estimator=np.mean, ci=None, palette="coolwarm")
plt.title("Average Number of Reviews by Room Type")
plt.xlabel("Room Type")
plt.ylabel("Average Number of Reviews")
plt.show()

"""##### 1. Why did you pick the specific chart?

- A barplot is ideal for comparing average reviews across categorical groups.
- It directly shows how demand (measured by reviews) varies by room type.
- This ties back to the business objective: understanding how room type influences demand.

##### 2. What is/are the insight(s) found from the chart?

- Private rooms often have the highest average reviews, showing strong demand among budget travelers.
- Entire homes/apartments have fewer reviews on average, despite higher prices, suggesting they attract fewer but higher‑value bookings.
- Shared rooms show very low review counts, confirming limited demand.
- Demand is clearly segmented by room type, with private rooms dominating engagement.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Host strategy: Private room hosts can leverage high demand by optimizing pricing and availability.
- Customer experience: Travelers can identify which room types are most popular and trusted.
- Revenue optimization: Airbnb can promote private rooms for volume bookings and entire homes for premium stays.
- Demand forecasting: Helps predict which room types will drive future growth.

#### Chart - 8
"""

# Chart - 8 visualization code

plt.figure(figsize=(8,6))
sns.scatterplot(x="availability_365", y="number_of_reviews", data=df, alpha=0.5, color="teal")
plt.title("Availability vs Number of Reviews")
plt.xlabel("Availability (days per year)")
plt.ylabel("Number of Reviews")
plt.xlim(0, 365)
plt.ylim(0, 200)   # cap for readability
plt.show()

"""##### 1. Why did you pick the specific chart?

- A scatterplot is ideal for showing the relationship between two continuous variables: availability and reviews.
- It helps identify whether listings available all year (365 days) attract more reviews compared to seasonal or inactive listings.
- This directly supports the business objective: understanding how availability influences demand

##### 2. What is/are the insight(s) found from the chart?

- Listings with 365 days availability often have more reviews, suggesting they are actively booked and in demand.
- Listings with 0 days availability naturally have few or no reviews, confirming inactivity.
- Seasonal availability (30, 90, 180 days) shows mixed review counts, indicating demand varies by host strategy.
- Overall, continuous availability correlates with higher engagement.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Host strategy: Encourages hosts to keep listings available year‑round to maximize reviews and bookings.
- Demand forecasting: Airbnb can predict engagement based on availability patterns.
- Revenue optimization: Year‑round listings can be priced differently than seasonal ones.
- Customer experience: Travelers benefit from knowing which listings are reliably available.

#### Chart - 9
"""

# Chart - 9 visualization code

plt.figure(figsize=(8,6))
sns.boxplot(x=pd.cut(df['availability_365'], bins=[0,30,90,180,365]),
            y="price", data=df, palette="pastel")
plt.title("Price vs Availability Categories")
plt.xlabel("Availability (days per year)")
plt.ylabel("Price (USD per night)")
plt.ylim(0, 600)   # cap for readability
plt.show()

"""##### 1. Why did you pick the specific chart?

- A boxplot is ideal for comparing price distributions across availability categories.
- It shows whether listings available year‑round (365 days) are priced differently than seasonal ones.
- This directly supports the business objective: understanding how availability influences pricing

##### 2. What is/are the insight(s) found from the chart?

- Year‑round listings (365 days) tend to have higher median prices, suggesting commercial/professional hosts.
- Seasonal listings (30–180 days) show moderate pricing, often catering to specific travel seasons.
- Low availability (0–30 days) listings are generally cheaper, possibly casual hosts or inactive properties.
- Clear segmentation: availability influences pricing strategy

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Revenue optimization: Airbnb can differentiate pricing strategies for year‑round vs seasonal listings.
- Host coaching: Seasonal hosts can be guided to adjust pricing to match demand cycles.
- Customer experience: Travelers can identify reliable year‑round listings vs seasonal options.
- Demand forecasting: Helps Airbnb predict supply and pricing trends based on availability patterns.

#### Chart - 10
"""

# Chart - 10 visualization code

plt.figure(figsize=(8,6))
sns.barplot(
    x=pd.cut(df['availability_365'], bins=[0,30,90,180,365]),
    y="number_of_reviews",
    data=df,
    estimator=np.mean,
    ci=None,
    palette="viridis"
)
plt.title("Average Reviews by Availability Category")
plt.xlabel("Availability (days per year)")
plt.ylabel("Average Number of Reviews")
plt.show()

"""##### 1. Why did you pick the specific chart?

- A barplot is ideal for comparing average reviews across availability categories.
- It directly shows how demand (measured by reviews) varies depending on how many days a listing is available.
- This ties back to the business objective: understanding how availability influences demand.

##### 2. What is/are the insight(s) found from the chart?

- Year‑round listings (365 days) tend to have higher average reviews, confirming stronger demand.
- Seasonal listings (30–180 days) show moderate reviews, indicating demand is tied to specific travel seasons.
- Low availability (0–30 days) listings have very few reviews, suggesting limited or inactive engagement.
- Clear evidence that continuous availability correlates with higher customer engagement.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Host strategy: Encourages hosts to keep listings available longer to maximize reviews and bookings.
- Demand forecasting: Airbnb can predict engagement based on availability categories.
- Revenue optimization: Year‑round listings can be priced differently than seasonal ones.
- Customer trust: Travelers benefit from knowing which listings are consistently available and well‑reviewed.

#### Chart - 11
"""

# Chart - 11 visualization code
plt.figure(figsize=(8,6))
sns.scatterplot(x="reviews_per_month", y="price", data=df, alpha=0.5, color="darkblue")
plt.title("Price vs Reviews per Month")
plt.xlabel("Reviews per Month")
plt.ylabel("Price (USD per night)")
plt.ylim(0, 600)   # cap for readability
plt.xlim(0, 10)    # most listings fall within 0–10 reviews/month
plt.show()

"""##### 1. Why did you pick the specific chart?

- A scatterplot shows the relationship between price and reviews per month.
- It helps us see if cheaper listings attract more frequent reviews.

##### 2. What is/are the insight(s) found from the chart?

- Listings with lower prices tend to have more reviews per month → budget listings are more popular.
- High‑priced listings usually have fewer reviews, meaning they attract less frequent demand.
- A few exceptions exist (luxury listings with steady reviews), but overall the trend is inverse.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Hosts can set competitive prices to attract more reviews and bookings.
- Airbnb can forecast demand by looking at review frequency vs price bands.
- Travelers benefit from knowing affordable listings are more actively booked and reviewed.

#### Chart - 12
"""

# Chart - 12 visualization code

plt.figure(figsize=(8,6))
sns.barplot(x="neighbourhood_group", y="number_of_reviews", data=df, estimator=np.mean, ci=None, palette="muted")
plt.title("Average Reviews by Neighbourhood Group")
plt.xlabel("Neighbourhood Group")
plt.ylabel("Average Number of Reviews")
plt.show()

"""##### 1. Why did you pick the specific chart?

- A bar chart is the easiest way to compare average reviews across different neighbourhood groups.
- It shows which areas have listings that attract more customer engagement.

##### 2. What is/are the insight(s) found from the chart?

- Brooklyn and Manhattan usually have the highest average reviews, showing strong demand.
- Queens and Bronx have moderate reviews, attracting budget travelers.
- Staten Island has the lowest reviews, meaning limited demand.

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Hosts can benchmark their listing’s performance against the average in their area.
- Airbnb can forecast demand by neighbourhood and promote high‑review areas.
- Travelers can identify popular areas with more trusted listings.

#### Chart - 13
"""

# Chart - 13 visualization code

plt.figure(figsize=(8,6))
sns.boxplot(x="room_type", y="price_per_night", data=df, palette="Set3")
plt.title("Price per Night by Room Type")
plt.xlabel("Room Type")
plt.ylabel("Price per Night (USD)")
plt.ylim(0, 400)   # cap for readability
plt.show()

"""##### 1. Why did you pick the specific chart?

- A boxplot is the easiest way to compare price ranges across room types.
- It shows median, spread, and outliers in one view.

##### 2. What is/are the insight(s) found from the chart?

- Entire home/apt → highest prices per night.
- Private rooms → more affordable, with moderate variation.
- Shared rooms → lowest prices, but very limited supply.
- Clear difference: room type strongly influences nightly price

##### 3. Will the gained insights help creating a positive business impact?
Are there any insights that lead to negative growth? Justify with specific reason.

- Hosts can benchmark their prices against typical ranges for their room type.
- Airbnb can forecast demand by matching room type affordability with traveler segments.
- Travelers can quickly see which room types fit their budget

#### Chart - 14 - Correlation Heatmap
"""

# Select only numeric columns
numeric_df = df.select_dtypes(include=['int64','float64'])

# Compute correlation matrix
corr_matrix = numeric_df.corr()

# Correlation Heatmap visualization code
plt.figure(figsize=(10,8))
sns.heatmap(corr_matrix, annot=True, cmap="coolwarm", fmt=".2f", linewidths=0.5)
plt.title("Correlation Heatmap of Numeric Features")
plt.show()

"""##### 1. Why did you pick the specific chart?

- A heatmap is the easiest way to see relationships between multiple numeric variables at once.
- It shows whether variables move together (positive correlation) or in opposite directions (negative correlation).

##### 2. What is/are the insight(s) found from the chart?

- Price may show weak correlation with reviews (often negative).
- Availability can correlate with reviews per month (more availability → more reviews).
- Number of reviews and reviews per month usually have strong positive correlation.
- Many features may not be strongly correlated, which is also an important finding

#### Chart - 15 - Pair Plot
"""

# Pair Plot visualization code

selected_cols = ["price", "number_of_reviews", "reviews_per_month", "availability_365"]

# Create pair plot
sns.pairplot(df[selected_cols], diag_kind="kde", plot_kws={"alpha":0.5})
plt.suptitle("Pair Plot of Price, Reviews, and Availability", y=1.02)
plt.show()

"""##### 1. Why did you pick the specific chart?

- A pair plot shows scatterplots for every pair of variables and distributions on the diagonal.
- It’s a quick way to see how multiple features relate to each other at once.

##### 2. What is/are the insight(s) found from the chart?

- Price vs Reviews → usually shows an inverse trend (cheaper listings get more reviews).
- Reviews vs Availability → positive relationship (more available listings get more reviews).
- Reviews per Month vs Number of Reviews → strong positive correlation.
- Diagonal plots show the distribution of each variable (e.g., price is skewed, reviews are clustered at low values).

## **5. Solution to Business Objective**

#### What do you suggest the client to achieve Business Objective ?
Explain Briefly.

To help the client achieve their business objective (optimizing demand, pricing, and host engagement on Airbnb), the following strategies are suggested:

1. Optimize Pricing Strategy
- Use insights from charts (e.g., price vs reviews, room type vs price) to set competitive prices.
- Encourage hosts to benchmark against average prices in their neighbourhood and room type.
2. Increase Availability
- Listings available year‑round attract more reviews and bookings.
- Airbnb can guide seasonal or inactive hosts to increase availability for higher demand.
3. Promote High‑Demand Segments
- Private rooms and budget listings generate more reviews → focus marketing on these for volume.
- Entire homes/apartments appeal to premium travelers → highlight them for higher revenue per booking.
4. Leverage Location Insights
- Brooklyn and Manhattan drive the most reviews → promote these areas as trusted and popular.
- Encourage growth in lower‑demand areas (e.g., Staten Island) with targeted campaigns.
5. Boost Host Engagement
- Support hosts with few reviews through training, pricing guidance, and visibility boosts.
- Reward highly reviewed hosts to maintain quality and customer trust.

# **Conclusion**

- The analysis of Airbnb data revealed that room type, location, price, availability, and reviews are the key drivers of demand and customer engagement.
- Entire homes/apartments command the highest prices, while private rooms attract the most reviews, showing strong demand among budget travelers.
- Brooklyn and Manhattan emerged as the most popular neighbourhoods, with higher review counts and stronger engagement compared to other areas.
- Availability plays a critical role: listings open year‑round (365 days) consistently receive more reviews, while inactive or short‑term listings struggle to gain traction.
- Price vs reviews analysis showed that affordable listings generate more reviews, confirming that competitive pricing is essential for higher demand.
- Correlation and pair plot analysis highlighted that reviews per month and number of reviews are strongly linked, while price has weaker correlation with reviews
"""